### ISSUE TITLE
The tilde key is different for international keyboards

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [jel-app/jel-mpl#2]
I would recommend to use a combination of letters rather than the tilde key.

Options or ideas
--------------

(Enter, Enter) to enter text
(Esc, Esc) to close

Ctrl+T to open and close text

Double click to start typing and a close button to stop typing

**Comment by gfodor** [comment]
hey @mauriciomartinez-itesm question about this - the keymap is actually the backtick key, but its the convention to call it the "tilde key" on US keyboards (yes its weird) -- does backtick work for your layout? what does Quake use to show the console? That is what I was leaning on. (crazy, I know)

**Comment by mauriciomartinez-itesm** [comment]
The one I have is the | key on the place of the tilde key, but I think there should be another approach to this since there are [a lot of keyboard layouts](https://sites.google.com/site/brightmeasurement/Home/keyboard-for-english-around-the-word) to consider.

My proposal would be to either change the hotkey to start entering text OR try using KeyboardEvent.code to get the physical position as seen on this [Mozilla Blog Post](https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/)

**Comment by gfodor** [comment]
Ah, that's super helpful, thanks! Convention-wise, do you know what Quake uses? I'm trying to lean on gamer muscle memory since tilde key is used to open consoles in FPS shooters typically.

**Comment by mauriciomartinez-itesm** [comment]
I haven't ever played Quake, sorry I don't think I'll be able to answer that

**Comment by gfodor** [comment]
Sure np. I'll see if I can find out.

**Comment by gfodor** [comment]
Ah, thank you internet - looks like it's physically where ~ key is on US keyboard.

**Comment by mauriciomartinez-itesm** [comment]
Works now perfectly!
